name: Build on Development Branches
on:
  push:
    branches:    
      - '*'         # matches every branch
      - '*/*'       # matches every branch containing a single '/'
      - '!master'   # excludes master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: yarn
      - name: Build
        run: yarn build
        env:
          VUE_APP_FB_API_KEY: ${{ secrets.VUE_APP_FB_API_KEY }}
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist
